# -*- coding: utf-8 -*-
"""Smart Product Recommendation Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8Hj_7HgeIw_ItgZv8I6o4bau0ZZu0Cb

Task 1:Smart Product Recommendation
Engine

Import the Pandas library for data manipulation.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from PIL import Image

"""Load the styles.csv dataset into a DataFrame."""

df = pd.read_csv("styles.csv", on_bad_lines="skip")

"""Display the dataset size (rows and columns)."""

print(df.head())

print(df.shape)

print(df.columns)

"""Select only the required columns from the dataset"""

df = df[
    [
        "id",
        "gender",
        "masterCategory",
        "subCategory",
        "articleType",
        "baseColour",
        "season",
        "usage",
        "productDisplayName"
    ]
]

"""Display the frequency of each product category."""

df.dropna(inplace=True)

df.reset_index(drop=True, inplace=True)

print(df.shape)

"""Show all unique product types available in the dataset."""

print(df["articleType"].value_counts().head(20))

print(sorted(df["articleType"].unique()))

"""Create rule-based complementary product mappings for recommendations."""

recommendation_rules = {

    "Running Shoes":[
        "Sports Sandals",
        "Track Pants",
        "Socks"
    ],

    "Casual Shoes":[
        "Jeans",
        "Tshirts",
        "Wallets"
    ],

    "Jeans":[
        "Tshirts",
        "Belts",
        "Casual Shoes"
    ],

    "Shirts":[
        "Formal Shoes",
        "Belts",
        "Trousers"
    ],

    "Tshirts":[
        "Jeans",
        "Casual Shoes",
        "Shorts"
    ]
}

def recommend_products(product):

    if product not in recommendation_rules:

        return []

    return recommendation_rules[product]

def fetch_products(product):

    recommendations = recommend_products(product)

    output = []

    for item in recommendations:

        result = df[
            df["articleType"].str.lower() == item.lower()
        ]

        if len(result) > 0:

            output.append(result.sample(1))

    if len(output) > 0:

        return pd.concat(output)

    return pd.DataFrame()

"""Test the recommendation system using "Running Shoes"."""

recommended = fetch_products("Running Shoes")

recommended

print("Input Product : Running Shoes")

print("\nRecommended Products:")

for i in recommend_products("Running Shoes"):

    print("•", i)

"""Visualize the recommendation distribution using a graph."""

recommended["articleType"].value_counts().plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Recommended Products")

plt.xlabel("Product")

plt.ylabel("Count")

plt.show()

IMAGE_FOLDER = "images/images"

def display_recommendations(df_products):

    n = len(df_products)

    fig, axes = plt.subplots(
        1,
        n,
        figsize=(4*n,5),
        dpi=180
    )

    if n == 1:
        axes = [axes]

    for ax, (_, row) in zip(axes, df_products.iterrows()):

        path = os.path.join(
            IMAGE_FOLDER,
            f"{int(row['id'])}.jpg"
        )

        if os.path.exists(path):

            img = Image.open(path)

            ax.imshow(img)

        else:

            ax.text(
                0.5,
                0.5,
                "Image Not Found",
                ha="center"
            )

        ax.set_title(
            row["articleType"],
            fontsize=11
        )

        ax.axis("off")

    plt.tight_layout()

    plt.show()

import zipfile

with zipfile.ZipFile("images (2).zip", "r") as zip_ref:
    zip_ref.extractall("images")

print("Extraction completed!")

recommended = fetch_products("Running Shoes")

display_recommendations(recommended)

recommended.to_csv(
    "recommended_products.csv",
    index=False
)

print("Recommendations saved successfully!")

"""Display recommendations with corresponding product images."""

product = input("Enter Product Name: ")

recommended = fetch_products(product)

if len(recommended) > 0:

    display_recommendations(recommended)

else:

    print("No recommendations found.")

"""Allow users to search by entering a product name."""

recommendation_rules = {

    "Running Shoes": ["Sports Sandals", "Track Pants", "Socks"],

    "Sports Shoes": ["Track Pants", "Socks", "Sports Sandals"],

    "Casual Shoes": ["Jeans", "Tshirts", "Wallets"],

    "Formal Shoes": ["Shirts", "Belts", "Trousers"],

    "Jeans": ["Tshirts", "Belts", "Casual Shoes"],

    "Tshirts": ["Jeans", "Casual Shoes", "Shorts"],

    "Shirts": ["Formal Shoes", "Belts", "Trousers"],

    "Shorts": ["Tshirts", "Casual Shoes"],

    "Track Pants": ["Running Shoes", "Sports Sandals", "Socks"],

    "Sports Sandals": ["Track Pants", "Socks"],

    "Socks": ["Running Shoes", "Sports Shoes"],

    "Wallets": ["Casual Shoes", "Belts"],

    "Belts": ["Jeans", "Formal Shoes"],

    "Sandals": ["Dresses", "Handbags"],

    "Flip Flops": ["Shorts", "Tshirts"],

    "Sweatshirts": ["Track Pants", "Sports Shoes"],

    "Kurtas": ["Leggings", "Sandals"],

    "Dresses": ["Heels", "Handbags"],

    "Handbags": ["Dresses", "Heels"],

    "Watches": ["Shirts", "Jeans", "Wallets"]

}

"""Display all available searchable product types."""

print("Available Products:\n")

for product in sorted(recommendation_rules.keys()):
    print("-", product)

print("\n")

product = input("Enter Product Name: ")

recommended = fetch_products(product)

if not recommended.empty:
    display_recommendations(recommended)
else:
    print("No recommendations found.")

"""Task 2 – Unique Product Catalog

Install SentenceTransformer and FAISS libraries.
"""

!pip install -q sentence-transformers faiss-cpu

"""Install SentenceTransformer and FAISS libraries."""

import pandas as pd
import numpy as np
import faiss

from sentence_transformers import SentenceTransformer

"""Import required Python libraries."""

df = pd.read_csv("styles.csv", on_bad_lines="skip")

df = df[
    [
        "id",
        "productDisplayName",
        "articleType",
        "baseColour",
        "gender",
        "usage"
    ]
]

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

print(df.shape)

"""Create a descriptive text representation for every product."""

df["description"] = (
    df["productDisplayName"] + " " +
    df["articleType"] + " " +
    df["baseColour"] + " " +
    df["gender"] + " " +
    df["usage"]
)

"""Load the pretrained SentenceTransformer model."""

model = SentenceTransformer("all-MiniLM-L6-v2")

sample_df = df.head(1000).copy()

embeddings = model.encode(
    sample_df["description"].tolist(),
    convert_to_numpy=True,
    show_progress_bar=True
)

embeddings = embeddings.astype("float32")

faiss.normalize_L2(embeddings)

"""Select the first 1000 products for testing."""

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embeddings)

print(index.ntotal)

"""Convert product descriptions into semantic embeddings."""

k = 5

distances, indices = index.search(
    embeddings,
    k
)

THRESHOLD = 0.90

visited = set()

groups = []

for i in range(len(sample_df)):

    if i in visited:
        continue

    group = []

    for score, idx in zip(distances[i], indices[i]):

        if score >= THRESHOLD:

            group.append(idx)

            visited.add(idx)

    groups.append(group)

unique_products = []

for group in groups:

    unique_products.append(
        sample_df.iloc[group[0]]
    )

unique_catalog = pd.DataFrame(unique_products)

print(unique_catalog.shape)

unique_catalog.to_csv(
    "unique_product_catalog.csv",
    index=False
)

print("Catalog Saved Successfully!")

"""Display groups of duplicate products."""

for group in groups[:5]:

    print("=" * 50)

    print(
        sample_df.iloc[group][
            [
                "productDisplayName",
                "articleType"
            ]
        ]
    )

"""Visualize the original versus unique catalog size."""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

plt.bar(
    ["Original Products", "Unique Products"],
    [len(sample_df), len(unique_catalog)]
)

plt.title("Duplicate Removal using AI Embeddings")

plt.ylabel("Number of Products")

plt.show()

"""Task 3 – Reverse Product Search

Install OpenCLIP and FAISS libraries.
"""

!pip install -q open_clip_torch faiss-cpu

"""Import all required libraries for image retrieval."""

import os
import faiss
import torch
import open_clip
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from tqdm import tqdm

"""Load the pretrained OpenCLIP model and configure the device (CPU/GPU)."""

device = "cuda" if torch.cuda.is_available() else "cpu"

model, _, preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)

tokenizer = open_clip.get_tokenizer("ViT-B-32")

model = model.to(device)
model.eval()

print("Model Loaded")

"""Create a working sample dataset."""

sample_df = df.head(1000).copy()

"""Verify the available dataset columns."""

print(sample_df.columns)

"""Import the os module for file path handling."""

import os

IMAGE_FOLDER = "images/images"

sample_df["image_path"] = sample_df["id"].apply(
    lambda x: os.path.join(
        IMAGE_FOLDER,
        f"{int(x)}.jpg"
    )
)

"""Specify the location of the image folder."""

IMAGE_FOLDER = "images"

"""Remove products whose images are unavailable."""

sample_df = sample_df[
    sample_df["image_path"].apply(os.path.exists)
].reset_index(drop=True)

print(sample_df.shape)

"""Display sample image paths for verification."""

print(sample_df[["id", "image_path"]].head())

"""Generate OpenCLIP image embeddings for all products"""

image_embeddings = []

for path in tqdm(sample_df["image_path"]):

    image = Image.open(path).convert("RGB")

    image = preprocess(image).unsqueeze(0).to(device)

    with torch.no_grad():
        embedding = model.encode_image(image)

    embedding = embedding.cpu().numpy().flatten()

    image_embeddings.append(embedding)

"""Convert image embeddings into a NumPy array"""

image_embeddings = np.array(image_embeddings).astype("float32")

print(image_embeddings.shape)

"""Normalize image embeddings for cosine similarity search"""

faiss.normalize_L2(image_embeddings)

"""Build a FAISS index using image embeddings."""

dimension = image_embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(image_embeddings)

print(index.ntotal)

"""Accept a text query from the user."""

query = input("Search Product : ")

"""Convert the text query into an OpenCLIP text embedding."""

text = tokenizer([query]).to(device)

with torch.no_grad():

    text_embedding = model.encode_text(text)

text_embedding = text_embedding.cpu().numpy().astype("float32")

faiss.normalize_L2(text_embedding)

print(text_embedding.shape)

"""Search the FAISS index for the most similar products."""

k = 5

scores, indices = index.search(
    text_embedding,
    k
)

"""Display the retrieved product details."""

results = sample_df.iloc[indices[0]]

results[
    [
        "productDisplayName",
        "articleType",
        "baseColour",
        "gender",
        "usage"
    ]
]

"""Verify dataset columns again."""

print(sample_df.columns.tolist())

"""Import the os module (used for path checking)."""

import os

IMAGE_FOLDER = "images/images"

sample_df["image_path"] = sample_df["id"].apply(
    lambda x: os.path.join(IMAGE_FOLDER, f"{int(x)}.jpg")
)

"""Define the image directory path."""

IMAGE_FOLDER = "images"

"""Verify image paths before visualization."""

print(sample_df[["id", "image_path"]].head())

"""Display the retrieved product images."""

import matplotlib.pyplot as plt
from PIL import Image
import os

plt.figure(figsize=(18,5))

for i, idx in enumerate(indices[0]):

    plt.subplot(1,5,i+1)

    img_path = sample_df.iloc[idx]["image_path"]

    if os.path.exists(img_path):

        img = Image.open(img_path)

        plt.imshow(img)

    else:

        plt.text(
            0.5,
            0.5,
            "Image Not Found",
            ha="center",
            va="center"
        )

    plt.title(
        sample_df.iloc[idx]["productDisplayName"][:20],
        fontsize=8
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

"""Print the similarity score for each retrieved product."""

for score, idx in zip(scores[0], indices[0]):

    print("-"*50)

    print("Product :", sample_df.iloc[idx]["productDisplayName"])

    print("Similarity :", round(float(score),3))